Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"


    config.vm.define "mysqldb" do |mysql|

      config.vm.provider "virtualbox" do |vb|
          vb.memory = 512
          vb.cpus = 1
          vb.name = "MYSQL"
      end
      config.vm.network "public_network", ip: "192.168.15.108", bridge: "enp2s0"

      config.vm.provision "shell",
        inline: "cat /configs/bionic-key.pub >> .ssh/authorized_keys"

      config.vm.synced_folder "./configs", "/configs"
      config.vm.synced_folder ".", "/vagrant", disable: true
  end
end