$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "public_network", ip: "192.168.1.108", bridge: "enp2s0"

  config.vm.provision "shell",
    inline: "cat /configs/bionic-key.pub >> .ssh/authorized_keys"

    config.vm.provision "shell",
          inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
      config.vm.provision "shell",
          inline: "service mysql restart"

  config.vm.provision "shell",
   inline: $script_mysql

  config.vm.synced_folder "./configs", "/configs"
  config.vm.synced_folder ".", "/vagrant", disable: true
end
